import React, { useState } from 'react';
import { Brain, Check, X, AlertCircle } from 'lucide-react';

export default function AIDraftReview() {
  // Mock data representing the response from GET /api/ai/drafts/:lessonId
  const [drafts, setDrafts] = useState([
    {
      _id: 'draft1',
      questionText: 'What is the primary purpose of an emergency fund?',
      options: [
        { text: 'To invest in high-risk stocks' },
        { text: 'To pay for regular monthly groceries' },
        { text: 'To cover unexpected financial shocks' },
        { text: 'To save for a luxury vacation' }
      ],
      correctOption: 2,
      explanation: 'An emergency fund provides a financial buffer for unexpected expenses, preventing you from going into debt.',
      difficulty: 'Easy'
    },
    {
      _id: 'draft2',
      questionText: 'Which of the following is considered a "need" rather than a "want"?',
      options: [
        { text: 'A new smartphone' },
        { text: 'Basic health insurance' },
        { text: 'Dining out at a restaurant' },
        { text: 'Designer clothing' }
      ],
      correctOption: 1,
      explanation: 'Health insurance protects against catastrophic medical costs, making it a fundamental financial need.',
      difficulty: 'Medium'
    }
  ]);

  const handleApprove = (id) => {
    // In a real app, this would trigger PATCH /api/admin/quizzes/:id { status: 'Published' }
    setDrafts(drafts.filter(d => d._id !== id));
  };

  const handleReject = (id) => {
    // In a real app, this would trigger DELETE /api/admin/quizzes/:id
    setDrafts(drafts.filter(d => d._id !== id));
  };

  return (
    <div className="animate-fadeInUp" style={{ maxWidth: 900, margin: '0 auto', paddingBottom: '3rem' }}>
      
      <div style={{ marginBottom: '2rem', display: 'flex', alignItems: 'center', gap: '1rem' }}>
        <div style={{ width: 48, height: 48, borderRadius: '12px', background: 'rgba(251,191,36,0.1)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--color-accent-gold)' }}>
          <Brain size={24} />
        </div>
        <div>
          <h1 style={{ fontSize: '2rem', fontWeight: 800, marginBottom: '0.25rem' }}>AI Draft Review</h1>
          <p style={{ color: 'var(--color-text-muted)' }}>Review and publish quiz questions generated by Gemini AI.</p>
        </div>
      </div>

      {drafts.length === 0 ? (
        <div className="glass" style={{ padding: '4rem 2rem', textAlign: 'center' }}>
          <Check size={48} color="var(--color-accent)" style={{ margin: '0 auto 1rem' }} />
          <h3 style={{ fontSize: '1.5rem', fontWeight: 700, marginBottom: '0.5rem' }}>All Caught Up!</h3>
          <p style={{ color: 'var(--color-text-muted)' }}>There are no pending AI drafts to review right now.</p>
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
          {drafts.map((draft, index) => (
            <div key={draft._id} className="glass" style={{ padding: '2rem', borderLeft: '4px solid var(--color-accent-gold)' }}>
              
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '1.5rem' }}>
                <h3 style={{ fontSize: '1.25rem', fontWeight: 700, flex: 1, paddingRight: '1rem', lineHeight: 1.4 }}>
                  <span style={{ color: 'var(--color-text-muted)', marginRight: '0.5rem' }}>Q{index + 1}.</span> 
                  {draft.questionText}
                </h3>
                <span style={{ padding: '0.25rem 0.75rem', background: 'rgba(255,255,255,0.05)', borderRadius: 99, fontSize: '0.8rem', fontWeight: 600 }}>
                  {draft.difficulty}
                </span>
              </div>

              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem', marginBottom: '1.5rem' }}>
                {draft.options.map((opt, i) => (
                  <div key={i} style={{ 
                    padding: '1rem', 
                    borderRadius: 8, 
                    background: i === draft.correctOption ? 'rgba(16,185,129,0.1)' : 'rgba(0,0,0,0.2)',
                    border: `1px solid ${i === draft.correctOption ? 'rgba(16,185,129,0.3)' : 'rgba(255,255,255,0.05)'}`,
                    display: 'flex',
                    alignItems: 'center',
                    gap: '0.75rem'
                  }}>
                    <div style={{ width: 24, height: 24, borderRadius: '50%', background: i === draft.correctOption ? 'var(--color-accent)' : 'var(--color-surface-2)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '0.8rem', fontWeight: 700 }}>
                      {['A', 'B', 'C', 'D'][i]}
                    </div>
                    <span style={{ fontSize: '0.95rem', fontWeight: i === draft.correctOption ? 600 : 400 }}>{opt.text}</span>
                  </div>
                ))}
              </div>

              <div style={{ background: 'rgba(99,102,241,0.05)', padding: '1rem', borderRadius: 8, border: '1px solid rgba(99,102,241,0.1)', marginBottom: '1.5rem' }}>
                <strong style={{ color: 'var(--color-primary-light)', display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem' }}><AlertCircle size={16}/> Explanation</strong>
                <p style={{ color: 'var(--color-text-muted)', fontSize: '0.95rem', lineHeight: 1.5 }}>{draft.explanation}</p>
              </div>

              <div style={{ display: 'flex', gap: '1rem', justifyContent: 'flex-end', borderTop: '1px solid var(--color-border)', paddingTop: '1.5rem' }}>
                <button onClick={() => handleReject(draft._id)} className="btn-ghost" style={{ color: 'var(--color-danger)' }}>
                  <X size={18} /> Discard
                </button>
                <button onClick={() => handleApprove(draft._id)} className="btn-primary" style={{ background: 'var(--color-accent)' }}>
                  <Check size={18} /> Approve & Publish
                </button>
              </div>

            </div>
          ))}
        </div>
      )}
    </div>
  );
}
