import React, { useState } from 'react';
import { Brain, Check, X, AlertCircle, Sparkles, CheckCircle2 } from 'lucide-react';
import DashboardLayout from '../../layouts/DashboardLayout';

export default function AIDraftReview() {
  const [drafts, setDrafts] = useState([
    {
      _id: 'draft1',
      questionText: 'What is the primary purpose of an emergency fund?',
      options: [
        { text: 'To invest in high-risk crypto assets' },
        { text: 'To pay for regular weekend entertainment' },
        { text: 'To cover unexpected financial shocks (medical, job loss)' },
        { text: 'To save for a luxury vacation trip' },
      ],
      correctOption: 2,
      explanation:
        'An emergency fund provides a financial cushion for unexpected events, ensuring you do not need to take high-interest loans.',
      difficulty: 'Easy',
    },
    {
      _id: 'draft2',
      questionText: 'Which of the following is considered a "need" under the 50/30/20 budgeting rule?',
      options: [
        { text: 'A new flagship smartphone' },
        { text: 'Basic health & term life insurance' },
        { text: 'Dining out at fine dining restaurants' },
        { text: 'Subscribing to 5 streaming services' },
      ],
      correctOption: 1,
      explanation:
        'Health insurance protects against catastrophic medical costs, making it a critical financial need.',
      difficulty: 'Medium',
    },
  ]);

  const handleApprove = (id) => {
    setDrafts(drafts.filter((d) => d._id !== id));
  };

  const handleReject = (id) => {
    setDrafts(drafts.filter((d) => d._id !== id));
  };

  return (
    <DashboardLayout>
      <div className="flex flex-col gap-6 animate-fadeInUp font-sans max-w-5xl mx-auto">
        {/* Header */}
        <div className="flex items-center gap-3 pb-3 border-b border-slate-200/80">
          <div className="w-10 h-10 rounded-xl bg-amber-50 border border-amber-100 flex items-center justify-center text-amber-600 shrink-0">
            <Brain className="w-5 h-5 stroke-[2]" />
          </div>
          <div>
            <h1 className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight">
              AI Draft Review Workflow
            </h1>
            <p className="text-xs sm:text-sm text-slate-500 font-normal mt-0.5">
              Review, edit, and publish draft quiz questions generated by Gemini AI before they reach learners.
            </p>
          </div>
        </div>

        {/* Draft List */}
        {drafts.length === 0 ? (
          <div className="bg-white border border-slate-200/90 rounded-2xl p-12 text-center shadow-2xs my-4">
            <div className="w-12 h-12 rounded-full bg-emerald-50 text-emerald-600 flex items-center justify-center mx-auto mb-3">
              <CheckCircle2 className="w-6 h-6" />
            </div>
            <h3 className="font-extrabold text-base text-slate-900 mb-1">
              All Drafts Reviewed!
            </h3>
            <p className="text-xs text-slate-500">
              There are no pending Gemini AI draft questions waiting for approval.
            </p>
          </div>
        ) : (
          <div className="flex flex-col gap-6">
            {drafts.map((draft, index) => (
              <div
                key={draft._id}
                className="bg-white border border-slate-200/90 rounded-2xl p-6 shadow-2xs flex flex-col gap-4 border-l-4 border-l-amber-500"
              >
                <div className="flex items-start justify-between gap-4">
                  <h3 className="font-extrabold text-base text-slate-900 leading-snug">
                    <span className="text-slate-400 font-normal mr-2">Q{index + 1}.</span>
                    {draft.questionText}
                  </h3>
                  <span className="px-2.5 py-0.5 rounded-md bg-slate-100 text-slate-700 text-[11px] font-semibold border border-slate-200 shrink-0">
                    {draft.difficulty}
                  </span>
                </div>

                {/* Options Grid */}
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  {draft.options.map((opt, i) => (
                    <div
                      key={i}
                      className={`p-3.5 rounded-xl border text-xs flex items-center gap-3 ${
                        i === draft.correctOption
                          ? 'bg-emerald-50 border-emerald-300 text-emerald-900 font-semibold'
                          : 'bg-slate-50 border-slate-200 text-slate-700'
                      }`}
                    >
                      <span
                        className={`w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold shrink-0 ${
                          i === draft.correctOption
                            ? 'bg-emerald-600 text-white'
                            : 'bg-slate-200 text-slate-600'
                        }`}
                      >
                        {['A', 'B', 'C', 'D'][i]}
                      </span>
                      <span>{opt.text}</span>
                    </div>
                  ))}
                </div>

                {/* Explanation Box */}
                <div className="bg-blue-50/60 border border-blue-100 p-3.5 rounded-xl text-xs text-slate-700 flex flex-col gap-1">
                  <span className="font-bold text-blue-900 flex items-center gap-1.5">
                    <Sparkles className="w-3.5 h-3.5 text-blue-600" />
                    Gemini AI Explanation:
                  </span>
                  <p className="text-slate-600 leading-relaxed font-normal">{draft.explanation}</p>
                </div>

                {/* Action Buttons */}
                <div className="flex items-center justify-end gap-3 pt-4 border-t border-slate-100">
                  <button
                    onClick={() => handleReject(draft._id)}
                    className="px-4 py-2 rounded-xl border border-red-200 text-red-700 hover:bg-red-50 text-xs font-semibold flex items-center gap-1.5 transition-colors"
                  >
                    <X className="w-4 h-4" />
                    <span>Discard Draft</span>
                  </button>
                  <button
                    onClick={() => handleApprove(draft._id)}
                    className="px-5 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold flex items-center gap-1.5 transition-all shadow-xs"
                  >
                    <Check className="w-4 h-4" />
                    <span>Approve & Publish</span>
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </DashboardLayout>
  );
}
